log_level: "trace" # trace, debug, info, warn, error, fatal, panic
http_server:
  host: "localhost"
  port: ":8080"
postgres:
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "password"
  DB_NAME: "fiber_book"